import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { recoverBuild } from "../build/build.mjs";
import { assertOwnedJavaScript } from "../build/check-generated.mjs";
import { readInventory } from "../build/common.mjs";

const root = process.env.THEGOALBUDDY_TEST_ROOT || process.cwd();

test("installed executable identifies its TypeScript source rather than handwritten JavaScript", () => {
  const source = readFileSync(resolve(root, "internal/cli/goal-maker.mjs"), "utf8").split("\n").slice(0, 2).join("\n");
  assert.match(source, /^#![^\n]+\n\/\/ Generated from internal\/cli\/goal-maker\.mts; do not edit\./);
});

test("generated inventory cannot grant ownership over README, goals or arbitrary outputs", () => {
  for (const output of ["README.md", "docs/goals/local/state.yaml", "../outside.mjs", "goalbuddy/scripts/unrelated.mjs"]) {
    assert.throws(() => readInventory({ version: 1, files: [{ source: "goalbuddy/scripts/a.mts", output, project: "node" }] }), /inventory|Inventory/);
  }
});

test("malformed recovery journal is rejected before any unowned file is removed", () => {
  const fixture = mkdtempSync(join(tmpdir(), "thegoalbuddy-journal-"));
  try {
    mkdirSync(join(fixture, ".build"));
    writeFileSync(join(fixture, "README.md"), "retain owner content");
    writeFileSync(join(fixture, ".build/promotion.json"), JSON.stringify({ version: 1, files: [{ path: "README.md", backup: null, temporary: "README.md.generated-123" }] }));
    assert.throws(() => recoverBuild(fixture), /Unsafe build journal/);
    assert.equal(readFileSync(join(fixture, "README.md"), "utf8"), "retain owner content");
    assert.ok(existsSync(join(fixture, ".build/promotion.json")));
  } finally { rmSync(fixture, { recursive: true, force: true }); }
});

test("rollback restores owned output and removes interrupted promotion temporary files", () => {
  const fixture = mkdtempSync(join(tmpdir(), "thegoalbuddy-rollback-"));
  try {
    mkdirSync(join(fixture, ".build/emit-fixture"), { recursive: true });
    mkdirSync(join(fixture, "goalbuddy/scripts"), { recursive: true });
    const backup = join(fixture, ".build/emit-fixture/backup-0");
    writeFileSync(backup, "previous generated bytes");
    writeFileSync(join(fixture, "goalbuddy/scripts/a.mjs"), "partial bytes");
    writeFileSync(join(fixture, "goalbuddy/scripts/a.mjs.generated-123"), "unfinished bytes");
    writeFileSync(join(fixture, ".build/promotion.json"), JSON.stringify({ version: 1, files: [{ path: "goalbuddy/scripts/a.mjs", backup, temporary: "goalbuddy/scripts/a.mjs.generated-123" }] }));
    recoverBuild(fixture);
    assert.equal(readFileSync(join(fixture, "goalbuddy/scripts/a.mjs"), "utf8"), "previous generated bytes");
    assert.equal(existsSync(join(fixture, "goalbuddy/scripts/a.mjs.generated-123")), false);
    assert.equal(existsSync(join(fixture, ".build/promotion.json")), false);
  } finally { rmSync(fixture, { recursive: true, force: true }); }
});

test("handwritten JavaScript cannot enter maintained trees outside generated ownership", () => {
  const fixture = mkdtempSync(join(tmpdir(), "thegoalbuddy-ownership-"));
  try {
    mkdirSync(join(fixture, "internal/cli"), { recursive: true });
    writeFileSync(join(fixture, "internal/cli/new.js"), "intentional invalid fixture");
    assert.throws(() => assertOwnedJavaScript(fixture, new Set()), /Unowned JavaScript/);
  } finally { rmSync(fixture, { recursive: true, force: true }); }
});


test("recovery rejects symlink ancestors before touching any owner file", () => {
  const fixture = mkdtempSync(join(tmpdir(), "thegoalbuddy-journal-symlink-"));
  const owner = mkdtempSync(join(tmpdir(), "thegoalbuddy-owner-"));
  try {
    mkdirSync(join(fixture, ".build"));
    mkdirSync(join(fixture, "goalbuddy"));
    symlinkSync(owner, join(fixture, "goalbuddy/scripts"), "dir");
    writeFileSync(join(owner, "a.mjs"), "retain owner bytes");
    writeFileSync(join(fixture, ".build/promotion.json"), JSON.stringify({ version: 1, files: [{ path: "goalbuddy/scripts/a.mjs", backup: null, temporary: "goalbuddy/scripts/a.mjs.generated-123" }] }));
    assert.throws(() => recoverBuild(fixture), /symlink/i);
    assert.equal(readFileSync(join(owner, "a.mjs"), "utf8"), "retain owner bytes");
    assert.ok(existsSync(join(fixture, ".build/promotion.json")));
  } finally { rmSync(fixture, { recursive: true, force: true }); rmSync(owner, { recursive: true, force: true }); }
});
